---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# GSADF.AAU

<!-- badges: start -->
<!-- badges: end -->

The goal of GSADF.AAU is to implement the bubble detection method of GSADF.

## Installation

You can install the released version of GSADF.AAU from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Rasmusdamaau/GSADF.AAU")
```



```{r}
library(GSADF.AAU)
gsadf <- GSADF(ticker = "btc-usd",
                          x = NULL,
                          min_window = 60,
                          step_length = 5,
                          window_increase = 10,
                          date_from = "2020-01-01",
                          date_to = "2020-12-01",
                          drift = F,
                          trend = F,
                          risk_free_rate = 0.01,
                          own_df_distribution = NULL)

head(gsadf)

```




```{r}

plot_GSADF(u = gsadf,
                      d = NULL,
                      d_t = NULL,
                      p_restrict = 0.95,
                      start_date_tq_get = "2020-01-01",
                      image_name = NULL,
                      valuta = "USD",
                      aktie = "Bitcoin")


```




```{r}

tabel_gsadf <- Tabel_GSADF(gsadf = gsadf)

tabel_gsadf


```

